name: SonarCloud Analysis with Quality Gate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install dependencies
        run: |
          # Installer vos dépendances, par exemple pour un projet Maven :
          mvn clean install

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=ssy-epsi_clean-code-with-sonar \
            -Dsonar.organization=ssy-epsi \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check the Quality Gate status
        run: |
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=ssy-epsi_clean-code-with-sonar" \
            | grep -q '"status":"ERROR"' && echo "Quality Gate failed" && exit 1 || echo "Quality Gate passed"
